const blogData = [
  {
    id: 1,
    image: "https://img.freepik.com/free-photo/engineer-working-construction-site_23-2148870185.jpg",
    category: "Contractors",
    date: { day: "04", month: "Mar" },
    title: "The Importance Of Quality Roofing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.",
  },
  {
    id: 2,
    image: "https://img.freepik.com/free-photo/engineers-standing-building-site_1303-15871.jpg",
    category: "Contractors",
    date: { day: "05", month: "Mar" },
    title: "Commercial Vs. Residential Construction",
    description: "Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo. Lorem ipsum dolor sit amet.",
  },
  {
    id: 3,
    image: "https://img.freepik.com/free-photo/construction-site-sunset_1127-3452.jpg",
    category: "Contractors",
    date: { day: "06", month: "Mar" },
    title: "Step-By-Step Guide To Planning",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar dapibus leo.",
  },
  {
    id: 4,
    image: "https://img.freepik.com/free-photo/worker-holding-safety-helmet_23-2148867171.jpg",
    category: "Safety",
    date: { day: "07", month: "Mar" },
    title: "Workplace Safety Tips",
    description: "Keep your workplace safe by following these essential safety guidelines.",
  },
  {
    id: 5,
    image: "https://img.freepik.com/free-photo/architect-working-project_23-2148538325.jpg",
    category: "Architecture",
    date: { day: "08", month: "Mar" },
    title: "Modern Architecture Trends",
    description: "Explore the latest trends and innovations in modern architecture.",
  },
  {
    id: 6,
    image: "https://img.freepik.com/free-photo/construction-crew-discussing_23-2148516723.jpg",
    category: "Teamwork",
    date: { day: "09", month: "Mar" },
    title: "Effective Construction Teamwork",
    description: "How good teamwork can boost efficiency and success on construction sites.",
  },
  {
    id: 7,
    image: "https://img.freepik.com/free-photo/construction-site-machinery_23-2148903312.jpg",
    category: "Machinery",
    date: { day: "10", month: "Mar" },
    title: "Top Construction Machinery",
    description: "A guide to essential machinery used in construction projects.",
  },
  {
    id: 8,
    image: "https://img.freepik.com/free-photo/civil-engineer-working-construction-site_23-2148870183.jpg",
    category: "Engineering",
    date: { day: "11", month: "Mar" },
    title: "Civil Engineering Basics",
    description: "Introduction to key civil engineering concepts and techniques.",
  },
  {
    id: 9,
    image: "https://img.freepik.com/free-photo/blueprints-on-desk_23-2148903315.jpg",
    category: "Planning",
    date: { day: "12", month: "Mar" },
    title: "Planning Your Construction Project",
    description: "Steps to plan your project effectively and avoid delays.",
  },
  {
    id: 10,
    image: "https://img.freepik.com/free-photo/construction-helmet_23-2148518867.jpg",
    category: "Safety",
    date: { day: "13", month: "Mar" },
    title: "Importance of Protective Gear",
    description: "Why protective gear is a must on every construction site.",
  },
];

export default blogData;
